[package]
edition = "2021"
name = "inspirer-foundation"
version = "0.1.0"

[dependencies]
async-trait = "0.1.52"
axum = {version = "0.4.3", optional = true}
config = "0.11.0"
log = "0.4.14"
sea-orm = {version = "0.5.0", default-features = false, features = ["sqlx-mysql", "runtime-tokio-rustls", "macros"]}
serde = {version = "1.0.133", features = ["derive"]}
thiserror = "1.0.30"
tokio = {version = "1.15.0", features = ["sync"]}
type-map = "0.5.0"

[features]
default = ["enable-axum"]
enable-axum = ["axum"]
